# Generated by Django 3.1.5 on 2021-01-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ghuri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
