# Generated by Django 3.1.5 on 2021-01-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghuri', '0003_auto_20210118_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
